[project]
name = "infrastructure"
version = "0.1.0"
requires-python = ">=3.13"
authors = [{ name = "CaseySparkz", email = "contact@caseysparkz.com" }]

[project.optional-dependencies]
dev = [
    "boto3>=1.42.21,<2.0.0",
    "dagger_infrastructure @ file:///Users/caseysparks/Documents/git/caseysparkz/infrastructure/.dagger",
    "ruff>=0.14.10,<1.0.0",
]

[tool.setuptools.packages.find]
where = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
