# Author:       Casey Sparks
# Date:         June 06, 2024
# Description:  Yamllint configuration for yamllint.yml workflow.
---
extends: "default"
rules:
  truthy: "disable"
  comments: "disable"
  comments-indentation: "disable"
  document-start:
    present: true
  colons:
    level: "warning"
  commas:
    level: "warning"
  empty-lines:
    level: "warning"
  hyphens:
    level: "warning"
  braces:
    level: "warning"
    max-spaces-inside: 1
  brackets:
    level: "warning"
    max-spaces-inside: 1
  indentation:
    level: "warning"
    indent-sequences: "consistent"
  line-length:
    max: 120
    level: "warning"
    allow-non-breakable-inline-mappings: true
ignore:
  - "**/node_modules/"
